server:
  port: 8765

spring:
  security:
    user:
      name: client
      password: client
  application:
    name: admin-service
  boot:
    admin:
      client:
        username: admin
        password: admin
        instance:
          metadata:
            user:
              name: admin
              password: admin

      discovery:
        ignored-services: gateway-server, auth-service, admin-service

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
